CREATE TABLE mst_wedding(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	men_name VARCHAR(150) NOT NULL,
	women_name VARCHAR(150) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE mst_greeting(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	wedding_id INT NOT NULL,
	name VARCHAR(200) NOT NULL,
	address VARCHAR(200) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	note TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX wedding_id(wedding_id) USING BTREE,
	FOREIGN KEY (wedding_id) REFERENCES mst_wedding(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE auth_user(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(150) NOT NULL UNIQUE,
	password VARCHAR(150) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE auth_role(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE auth_user_role(
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	INDEX user_id(user_id) USING BTREE,
	INDEX role_id(role_id) USING BTREE,
	FOREIGN KEY (user_id) REFERENCES auth_user(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (role_id) REFERENCES auth_role(id) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO auth_role (name) VALUES ('admin');